# Generated by Django 5.0.3 on 2024-04-07 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('None', 'None'), ('STD', 'Standard'), ('PRM', 'Premium')], db_column='type', max_length=100)),
                ('cost', models.FloatField(db_column='cost')),
                ('is_active', models.BooleanField(default=False)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
