# Generated by Django 5.0.4 on 2024-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_subscription_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
