# Generated by Django 5.0.3 on 2024-03-15 19:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.UUID('192d23a0-8486-41bf-8c68-f85a1f28e089'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('is_premium', models.BooleanField(db_column='premium', default=False, verbose_name='Is Premium')),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
